name: "Release"
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    name: "GitHub Pages deployment"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code and set up web build"
        uses: actions/checkout@v3
        with:
          path: gh-pages
          fetch-depth: 0
      - name: "Print paths"
        run: |
          echo "PWD: $PWD"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          ls -la $PWD
          ls -la $GITHUB_WORKSPACE
      - name: "Deploy"
        working-directory: gh-pages
        run: |
          # Push orphan branch to gh-pages
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force --set-upstream origin gh-pages
          
