name: "Release"
on:
  push:
    branches:
      - master
jobs:
  gh-pages:
    name: "GitHub Pages deployment"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code and set up web build"
        uses: actions/checkout@v3
        with:
          path: gh-pages
          fetch-depth: 0
      - name: "Deploy"
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: gh-pages # The folder the action should deploy.
          clean: true
          single-commit: true
